---
title: "Index.rmd"
author: "Giulia Minnucci,Daniel Jemberu, Rose-Camille Vincent"
date: "20 novembre 2014"
output: html_document
---
```{r, echo=FALSE,results='asis',include=FALSE}
library(WDI)
healthpublicexpend<-WDI(indicator= c('SH.XPD.PUBL','SH.XPD.PCAP','SH.STA.ACSN'))
Benin<-subset(healthpublicexpend,country=='Benin')
Benin$iso2c<-NULL
names(Benin)[names(Benin)=="year"] <- "Year"
names(Benin)[names(Benin)=="SH.XPD.PUBL"] <- "Public.Health.Expenditure"
names(Benin)[names(Benin)=="SH.XPD.PCAP"] <- "Health.Expenditure.Per.Capita"
names(Benin)[names(Benin)=="SH.STA.ACSN"] <- "Improved.Sanitation.Facilities"
```

```{r,include=FALSE, message=FALSE}
library(googleVis)
```

```{r,include=FALSE, results='asis'}
compare_trend <-data.frame(
  Year=c("2005","2006","2007","2008","2009","2010","2011"),
  Public.Health.Expenditure=c(49.69487,50.22141,50.75158,50.95043,53.35198,51.16728,52.10150),
  Health.Expenditure.Per.Capita=c( 25.21300,26.47114,28.77537,31.01608,31.80012,30.47805,33.73303),
  Improved.Sanitation.Facilities=c(11.2,11.7,12.2,12.7,13.2,13.7,14.2))
```

```{r,echo=FALSE, results='asis'}
line_plot <- gvisLineChart(compare_trend)
print(line_plot, tag = 'chart')
```


```{r, include=FALSE}
library(RCurl)
library(foreign)  
#url version to be edited 
url <- "https://raw.githubusercontent.com/giumin/Third_Assignment/master/decentral.csv"
decentralization.data <- getURL(url)                
decentralization.data <- read.csv(textConnection(decentralization.data))

```

```{r,include=FALSE}
#URl to be edited 

url2 <- "https://raw.githubusercontent.com/giumin/Third_Assignment/master/health.csv"
health.data <- getURL(url2)                
health.data <- read.csv(textConnection(health.data))

decenthealth <-merge(decentralization.data,health.data, by=c("Year", "ID", "Cities"), all=TRUE)
```


```{r echo=FALSE, results='asis'}
library(ggmap)
qmap('benin')
```



